In [1]:
import numpy as np

def conv2D(matrix, kernel):
    # Get the dimensions of the input matrix
    m, n = matrix.shape
    
    # Create a padded matrix with zero padding
    padded_matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)
    
    # Initialize the output matrix
    output_matrix = np.zeros((m, n))
    
    # Perform the convolution operation
    for i in range(m):
        for j in range(n):
            # Extract the 3x3 region from the padded matrix
            region = padded_matrix[i:i+3, j:j+3]
            # Compute the convolution (element-wise multiplication and sum)
            output_matrix[i, j] = np.sum(region * kernel)
    
    return output_matrix


In [4]:

# Example usage
matrix = np.array([[2 for x in range(7)],
                   [2 for x in range(7)],
                   [(15 if (2<= x<= 4)else 2) for x in range(7)],
                   [(15 if (2<= x<= 4)else 2) for x in range(7)],
                   [(15 if (2<= x<= 4)else 2) for x in range(7)],
                   [2 for x in range(7)],
                   [2 for x in range(7)],
                   ])

kernel = np.array([[-1, 0, 1],
                   [-1, 0, 1],
                   [-1, 0, 1]])

output = conv2D(matrix, kernel)
print('ouput: \n',output)
print('original matrix\n',matrix)
print('kernel\n',kernel)

ouput: 
 [[  4.   0.   0.   0.   0.   0.  -4.]
 [  6.  13.  13.   0. -13. -13.  -6.]
 [  6.  26.  26.   0. -26. -26.  -6.]
 [  6.  39.  39.   0. -39. -39.  -6.]
 [  6.  26.  26.   0. -26. -26.  -6.]
 [  6.  13.  13.   0. -13. -13.  -6.]
 [  4.   0.   0.   0.   0.   0.  -4.]]
original matrix
 [[ 2  2  2  2  2  2  2]
 [ 2  2  2  2  2  2  2]
 [ 2  2 15 15 15  2  2]
 [ 2  2 15 15 15  2  2]
 [ 2  2 15 15 15  2  2]
 [ 2  2  2  2  2  2  2]
 [ 2  2  2  2  2  2  2]]
kernel
 [[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
